version: '3.8'
services:
  database:
    image: postgres:16
    container_name: database
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: trendybids
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: trendybids_db
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
